### ISSUE TITLE
Enable iOS h264 support

### ISSUE THREAD

**Issue by rayvbr** [pristineio/webrtc-build-scripts#109]
A few weeks ago, h264 hardware support was added. Currently, this requires setting the 'rtc_use_objc_h264' compile time flag. It would be great if this could be added to the build scripts and the pre-compiled builds.

**Comment by bwilks128** [comment]
I just tried building the latest library (9554). I have been using a much older library from January but wanted to see how the latest version works. (The new library needed the VideoToolbox.framework added to link properly.)

With the latest library, I am getting just a black rectangle for my local video. Could this be related to this issue or does not having this flag simply mean it doesn't use h264 acceleration? Are you seeing a black video screen for local video as well?

Thanks.

**Comment by ArikYa** [comment]
Usually black local view means the local camera wasn't opened correctly. Are you using any video constraints?

**Comment by bwilks128** [comment]
I don't believe so. Using the older library works fine.

**Comment by bwilks128** [comment]
I take that back. You are absolutely correct. I do have some constraints in place to lower the resolution and frame rate in order to stop the video from lagging. Commenting them out does show the local view.

With some experimentation, it appears that it is setting the resolution to 320x240 that is causing the failure. Given setting the frame rate does not do anything (and the frame rate is what I really want to change), it looks like this is a problem for me until the Google folks fix the issue where setting a frame rate constraint on iOS doesn't actually change anything.

Thanks for your on target help. Sorry for adding an unrelated topic to this thread.

**Comment by wlaurance** [comment]
To link correctly, I had to add `VideoToolbox.framework`. Is this related?

**Comment by ArikYa** [comment]
as bwilks128 confirmed, the issue was related to the video constraints. The current version will only do 640x480

**Comment by Basscord** [comment]
Hi all,

If I'm reading this correctly, @bwilks128 bug was unrelated to the original feature request.

The original request:
>A few weeks ago, h264 hardware support was added. Currently, this requires setting the 'rtc_use_objc_h264' compile time flag. It would be great if this could be added to the build scripts and the pre-compiled builds.

Is it possible this is still in the pipeline?

Thanks in advance!

**Comment by divyamML** [comment]
I am trying to set the video codec to h.264, for this I changed GYP_DEFINES="chromium_ios_signing=0" to GYP_DEFINES="chromium_ios_signing=0 use_objc_h264=1" in function wrbase in build.sh. However the offer still has vp8 in it instead of h264, not sure what I am missing here.

**Comment by divyamML** [comment]
nvm got it to work in the debug lib

**Comment by contra** [comment]
Did anyone figure this out?

**Comment by Lenne231** [comment]
Is there any progress on this?

**Comment by ibc** [comment]
Same problem here. I don't find any `build/common.gypi` in which I can set [use_objc_h264](https://chromium.googlesource.com/external/webrtc/trunk/webrtc/+/master/build/common.gypi#142)
