### ISSUE TITLE
Current version crashes with unrecognized selector on iOS

### ISSUE THREAD

**Issue by deanrock** [pristineio/webrtc-build-scripts#173]
Building current iOS version via get_webrtc & build_webrtc succeeds, but I get uncaught exception when running the application:

> state changed RTCSignalingState(rawValue: 0): RTCSignalingStable
> ice connection changed RTCICEConnectionState(rawValue: 1)
> 2016-04-11 16:18:22.480 DemoApp[4089:981708] -[RTCAudioSession isConfiguredForWebRTC]: unrecognized selector sent to instance 0x16848090
> 2016-04-11 16:18:22.481 DemoApp[4089:981708] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RTCAudioSession isConfiguredForWebRTC]: unrecognized selector sent to instance 0x16848090'
> *** First throw call stack:
> (0x24b7010b 0x24316e17 0x24b75925 0x24b73559 0x24aa3c08 0x19c885 0x1954d7 0x1952d1 0x39dff5 0x39df93 0x2ec5eb 0x2ed6e3 0x326d5f 0x32804f 0x32ee3b 0x2c8db1 0x2ba695 0x2c8bb1 0x2c8a9f 0x248a985b 0x248a97cf 0x248a7724)
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ArikYa** [comment]
This sounds like a WebRTC issue and not a build scripts issue. See if [this](https://bugs.chromium.org/p/webrtc/issues/detail?id=5742) helps

**Comment by ianmorty** [comment]
@deanrock did you get any further with this ?

**Comment by deanrock** [comment]
@ianmorty no, I gave up on trying to fix it.

**Comment by KamyarGhajar** [comment]
Check if you have the Microphone access permission before setting up an RTC call on iOS

**Comment by hardikdarji** [comment]
I have a same issue:
-[RTCAudioTrack setEnabled:forSegmentAtIndex:]: unrecognized selector sent to instance 0x15de3a60
2017-08-17 19:58:15.477321+0530 AppRTC[306:41898] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RTCAudioTrack setEnabled:forSegmentAtIndex:]: unrecognized selector sent to instance 0x15de3a60'
*** First throw call stack:
(0x1dbc7b3d 0x1ce4f067 0x1dbccfd1 0x1dbcb0c3 0x1daf3dc8 0x33d41 0x2bdb5 0x22e27785 0x22e27719 0x22e11d49 0x22e27055 0x2337933b 0x23375c53 0x1db83803 0x1db81a55 0x1db82017 0x1dad51af 0x1dad4fd1 0x1f27fb41 0x22e56e13 0x2ea6f 0x1d2c24eb)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any help?
