### ISSUE TITLE
SocketRocket dependency interference

### ISSUE THREAD

**Issue by bruun** [pristineio/webrtc-build-scripts#40]
We use the libjingle_peerconnection pod. The AppRTC example app recently switched to using the third party library `SocketRocket`, which is therefore now included in the library created by this build script. 

We already use the `SocketRocket` library in our app, which causes duplicate symbols in our project. The issue is described [here](http://guides.cocoapods.org/using/troubleshooting.html#can-i-workaround-duplicate-symbol-errors-with-static-libraries).

I'm a bit confused as to why the example app libraries are included in the binary at all. Could they either be removed, or at least prefixed in order to avoid duplicate symbol errors?

**Comment by thebehera** [comment]
Absolutely. I havent really done much testing, but go to https://github.com/pristineio/webrtc-build-scripts/blob/master/ios/build.sh#L21 set the target to libjingle_peerconnection_objc . Right now it is set to AppRTCDemo to help users run the demo app.  Thanks for the heads up! -- Will close when tested and fixed

**Comment by rwickliffe** [comment]
Changing the target to libjingle_peerconnection_objc built successfully for me, but the resulting output had only the libjingle_peerconnection_objc object files. I'm not very familiar with gyp files, but adding a new shared_library target to libjingle_examples.gyp with libjingle_peerconnection_objc as a dependency seems to kick out all the object files as expected and fixes the SocketRocket duplicate symbols issue. I suspect this approach is not ideal - I'd love to hear a better or proper solution.

**Comment by EricDavies** [comment]
Setting the target to libjingle_peerconnection_objc resulted in 19 missing symbols, probably what rwickliffe encountered. I went back to clean copy of the code and simply renamed my copy of the SocketRocket symbols so they didn't conflict. However, my app is still going off into never land with the new code. Can you give me the date at which the SocketRocket files were added to the library so I try pulling down a version that doesn't complicate my life :-).

Thank you.

**Comment by rwickliffe** [comment]
As best as I can tell, it was first added in r7852:
https://code.google.com/p/webrtc/source/detail?r=7852

**Comment by EricDavies** [comment]
Thank you! I’ll try 7851 then.

Eric.

**Comment by paynerc** [comment]
I recently stumbled upon this repo after spending a bunch of cycles building my own scripts to do pretty much the same thing. I also hit this issue and it was a bit maddening. My first course of action was to rm the libSocketRocket.a file before using libtool to make the library. This worked for my original case where I was trying to integrate into a prototype project that was using an "unnamespaced" SocketRocket. All was happy. Now, however, when I try to link that same library into a project with no SocketRocket, it complains about missing the SocketRocket symbols.

I am trying to understand the underlying ninja config files so that I can build all of the necessary libjingle goodness without having any of the demo code sneaking in. Hopefully between all of us we can make that happen.. And soon. :)

**Comment by paynerc** [comment]
From what I can tell, when you specify the target as `libjingle_peerconnection_objc`, it is indeed only building the sources listed for that target. It doesn't appear to honor the listed dependency on `libjingle_peerconnection`.

**Comment by paynerc** [comment]
OK. While I would like to say I have the solution on how to build without the demo, that I have not... However, during the `libtool` phase, we can exclude `libapprtc_signaling.a` and `libsocketrocket.a`, thus ignoring code in the project that is only for the demo.

**Comment by rwickliffe** [comment]
If you just want to build without the demo, as I mentioned above, adding a new shared_library target to `libjingle_examples.gyp` with `libjingle_peerconnection_objc` as a dependency seems to work. Something like the following:
```
{ 'target_name': 'libvineya',
  'type': 'shared_library',
  'dependencies': [
    'libjingle.gyp:libjingle_peerconnection_objc',
  ],
  'sources': [
  ],
  'export_dependent_settings': [
    'libjingle.gyp:libjingle_peerconnection_objc',
  ],
},
```
Whether this is the proper approach is debatable. There is a lot more info available here for anyone who wants to really dig in:
https://code.google.com/p/gyp/wiki/InputFormatReference

**Comment by paynerc** [comment]
My concern with that approach is that you have to modify source files that you are pulling down from the WebRTC project. I'd rather modify the build script once and not have to worry about having to modify the file should they update libjingle_examples.gyp.

The best approach would be to figure out how to force ninja to build all the dependencies of a static library since that is what seems to be the issue. Since libjingle_peerconnection_objc is listed as a static library it just builds the files specified in the library since it's not linking dependencies in with it.

--sent from the iPhone

**Comment by rwickliffe** [comment]
I share your concern and actually just saw your pull request - that is a nice solution. I considered just applying a patch to update `libjingle_examples.gyp` as part of the build process but hadn't gone down that road yet. This looks less brittle.

The language for [Linking Dependencies](https://code.google.com/p/gyp/wiki/InputFormatReference#Linking_Dependencies) didn't look promising to me for forcing ninja to alter the static library behavior. Admittedly, I haven't put in enough time familiarizing myself with ninja and gyp. Here's hoping it can be done to avoid the workarounds!

**Comment by paynerc** [comment]
I did some more reading and playing around. There is nothing that I have seen that will cause all of the other static libraries to be built short of invoking an executable target, like the demo, or a shared library target, like @rwickliffe showed above.

Either approach will work... Until the WebRTC folks add some other dependency to the demo that we must then remember to strip out. :/

**Comment by thebehera** [comment]
@paynerc  I'm probably going to push a new commit by injecting @rwickliffe 's similar code into the libjingle_examples file. This way we don't build any extra files, speeding up build time (ever so slightly)

**Comment by thebehera** [comment]
Also another reason is that this way we can remove code signing from the application

**Comment by paynerc** [comment]
Works for me. If you automate the injection of that target that'd be great since it's not something that we'd have to do manually every time you pulled the latest.

I was just going to send a message letting you know that I was troubleshooting an issue with my branch due to me stupidly using $@ instead of the two variables separately.



--sent from the iPhone

**Comment by thebehera** [comment]
@paynerc  have you tried the latest? It shouldn't include socket rocket

**Comment by paynerc** [comment]
I have not. Funny, though, as I was just checking in to see if anything changed. Will pull now and give it a shot.

**Comment by paynerc** [comment]
:+1: 

I would say that you can close this issue now, @thebehera.

**Comment by bruun** [comment]
Fantastic, the latest build works as expected in our project :+1:
