### ISSUE TITLE
Build scripts are creating every time the same jar library.

### ISSUE THREAD

**Issue by forlayo** [pristineio/webrtc-build-scripts#81]
Hello gentlemen,

I'm trying to do another build with latest webrtc code but when I go to libjingle_peerconnection_build directory I can see the very same jar file that I had created at 5 of feb.

I've tried also removing this directory, build scripts recreated it and add into it the same jar with modification date from 5 of feb.

There's any way to clean all and create everything ?

I'm doing..
- get_webrtc
- build_apprtc

Regards.

**Comment by ArikYa** [comment]
@forlayo, you should remove all the out* directories, that's where all the build process takes place, the ibraries are then copied over to libjingle_peerconnection_build.
The issue is that the WebRTC team changed the location of the output jar file. The scripts were updated 3 days ago to reflect ths, so make sure you are using the latest version of the scripts

**Comment by forlayo** [comment]
Thanks a lot guy! ;) With latest revison of scripts that doesn't occurs anymore.
